import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { SupabaseProvider } from "@/providers/supabase";
import { DatabaseProvider } from "@/providers/db";
import { AIProvider } from "@/providers/ai";
import { DocProvider } from "@/providers/doc";
const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.variable
        )}
      >
        <SupabaseProvider>
          <DatabaseProvider>
            <AIProvider>
              <DocProvider>
                <ThemeProvider
                  attribute="class"
                  defaultTheme="system"
                  enableSystem
                  disableTransitionOnChange
                  forcedTheme="dark"
                >
                  {children}
                  <Toaster />
                </ThemeProvider>
              </DocProvider>
            </AIProvider>
          </DatabaseProvider>
        </SupabaseProvider>
      </body>
    </html>
  );
}
